const express = require('express');
const router = express.Router();

const sendMail = (email, token) => {
    const nodemailer = require('nodemailer');
    const transport = nodemailer.createTransport({
        host: "smtp.mailtrap.io",
        port: 2525,
        auth: {
            user: "7b92aef383a566", //generated by Mailtrap
            pass: "2f783a751d733d" //generated by Mailtrap
        }
    });

    const mailOptions = {
        from: '<support@sec4you.com>',
        to: `${email}`,
        subject: 'Your Token',
        text: 'Hey there, it’s your token ;) ',
        html: `<b>Hey there! Take your token! </b><br> This is your token ${token} first message sent with Nodemailer`
    };

    transport.sendMail(mailOptions, (error, info) => {
        if (error) {
            return console.log(error);
        }
        console.log('Message sent: %s', info.messageId);
    });
}

router.get('/', (req, res, next) => { //post
    (() => {
        sendMail(req.query.email, req.query.token);
        res.status(200).send({
            email: req.query.email,
            token: req.query.token
        });
    })()
});

module.exports = router;
